root = "."
testdata_dir = "testdata"
tmp_dir = ".air"

[build]
  args_bin = []
  bin = "./.air/main"
  cmd = "go build -o ./.air/main ./cmd/api/main.go"
  exclude_dir = ["target", "vendor", "test", "docs", ".air"]
  exclude_file = []
  exclude_regex = ["_test.go"]
  follow_symlink = true

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[misc]
  clean_on_exit = true

[screen]
  clear_on_rebuild = true
  keep_scroll = true 
  