name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.25'

    - name: Lint
      uses: golangci/golangci-lint-action@v8
      with:
        version: v2.4.0

    - name: Security Check
      uses: securego/gosec@master
      with:
        args: ./...

    - name: Build
      run: make build

    - name: Test
      run: make test
